### ISSUE TITLE
‘No module named makebboxproposals’

### ISSUE THREAD

**Issue by akb46mayu** [makhtar17004/orientation-aware-firearm-detection#1]
Hi @makhtar17004,
Your repo was really cool. I was trying to use your repository, but I got an error:  ‘No module named makebboxproposals.’
In the directory of root/lib/rpn/ , I could not find two modules: makebboxproposals, and ftMap_Warp_2. 
Are there any ways to get those modules(py scripts).
Thanks.

**Comment by akhtarvision** [comment]
Missing files have been added
